### ISSUE TITLE
[BUG] python use python -m grpc_tools.proto gen code get ModuleNotFoundError: No module named 'buf'

### ISSUE THREAD

**Issue by dobet** [bufbuild/protovalidate-python#147] opened 2024-05-23 03:53 UTC
## Description

one proto file gen go and python code. go run success, but python run get 
ModuleNotFoundError: No module named 'buf'

## Steps to Reproduce

1. First step to reproduce the bug
proto
```
syntax = "proto3";
  
package my.package;

import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

message Transaction {
  uint64 id = 1 [(buf.validate.field).uint64.gt = 999];
  google.protobuf.Timestamp purchase_date = 2;
  google.protobuf.Timestamp delivery_date = 3;

  string price = 4 [(buf.validate.field).cel = {
    id: "transaction.price",
    message: "price must be positive and include a valid currency symbol ($ or £)",
    expression: "(this.startswith('$') or this.startswith('£')) and float(this[1:]) > 0"
  }];

  option (buf.validate.message).cel = {
    id: "transaction.delivery_date",
    message: "delivery date must be after purchase date",
    expression: "this.delivery_date > this.purchase_date"
  };
}
```
3. Second step to reproduce the bug

go use protoc to gen code and run sucess.

python use 
```
python3 -m grpc_tools.protoc 
```
to gen code and run falied

5. Third step to reproduce the bug
... additional steps as needed 

## Expected Behavior

python run success.

## Actual Behavior

ModuleNotFoundError: No module named 'buf'

## Environment

- **Operating System**: 
- **Version**: 
- **Compiler/Toolchain**: 
- **Protobuf Compiler & Version**: 
- **Protoc-gen-validate Version**: 
- **Protovalidate Version**:

**Comment by emcfarlane** [comment] 2024-06-11 16:13
Closing as a duplicate of #146 . Please see the fix in that thread.

**Closed by emcfarlane** 2024-06-11 16:13 UTC
Labels: Bug

**Comment by emcfarlane** [comment] 2024-06-11 18:20
@dobet you will need to compile the proto source files with protoc. The source files are contained within this repo: https://github.com/bufbuild/protovalidate/tree/main/proto . Once downloaded you can use `protoc` to generated the python files:
```
python3 -m grpc_tools.protoc \
  -I . \
  -I path/to/validate/ \
  --python_out=":./gen" 
```
Ensure the runtime matches the intended python version.
